### ISSUE TITLE
Geode Mod Description doesn't show the screenshot

### ISSUE THREAD

**Issue by zipatton** [Weebifying/coins-in-pause-menu-geode#2]
The image doesn't show up and just says "Screenshot"

<details>

<summary> Image </summary>

![20240314125457_1](https://github.com/Weebifying/coins-in-pause-menu-geode/assets/155669622/7f6986d4-1a69-4a87-8f13-d573bb50166d)

</details>

**Comment by Weebifying** [comment]
what is your platform

**Comment by zipatton** [comment]
> what is your platform

Windows. Lastest version of Geode (Beta.22)

**Comment by Weebifying** [comment]
then its probably some sort of geode's unzipping issues, not my problem :D
