### ISSUE TITLE
Show coins of the current run

### ISSUE THREAD

**Issue by kynex7510** [Weebifying/coins-in-pause-menu-geode#3]
I think it would be a good addition to show the coins collected in the current run, perhaps faded slightly to differentiate them from those already collected.

**Comment by Weebifying** [comment]
you are quite literally asking me to do the impossible lmao

**Comment by kynex7510** [comment]
How?

**Comment by Weebifying** [comment]
heyyy so maybeee its not so impossible lmao

**Comment by kynex7510** [comment]
you have the big silly

**Comment by Weebifying** [comment]
can you try the latest build to see if theres any issue?
https://github.com/Weebifying/coins-in-pause-menu-geode/actions/runs/8416220377
