### ISSUE TITLE
Display bug on Non 16:9 screen for betterpause

### ISSUE THREAD

**Issue by Naxrin** [Weebifying/coins-in-pause-menu-geode#5]
![image](https://github.com/Weebifying/coins-in-pause-menu-geode/assets/94737247/781a0213-0790-4eaa-b534-94b2948ef205)
Also betterpause now has coins display so it's not necessary to fit it anymore

**Comment by Weebifying** [comment]
i am going to become the joker

**Comment by Naxrin** [comment]
*hug(?
still thanks for ur tool
