### ISSUE TITLE
Coins cannot be seen on first better pause setting

### ISSUE THREAD

**Issue by RogerDHD** [Weebifying/coins-in-pause-menu-geode#6]
I don't know if it is because of the radio aspect of my screen, although in other better pause configurations they are visible

![Screenshot_20240404_192242_Geode](https://github.com/Weebifying/coins-in-pause-menu-geode/assets/67222080/cdd5bceb-569e-4313-93e6-a8787eb672d7)

**Comment by Weebifying** [comment]
intended, please enable the coins viewer option in BetterPause's settings

**Comment by RogerDHD** [comment]
Is it intended? Oh.. It's a shame honestly, I really liked how it looked, I think I'm going to downgrade I'm sorry

**Comment by Weebifying** [comment]
thats fine but you should check [this issue](https://github.com/Weebifying/coins-in-pause-menu-geode/issues/5)

**Comment by RogerDHD** [comment]
I see, I was trying for 10 minutes to find another place where they could be put but the problem is that apparently betterpause not only puts things together but also orders them differently in each radio aspect, the only thing I can think of would be a checkbox in the settings to disable it or not in case of problems :/
