### ISSUE TITLE
Coin Blinking doesn't work with better pause

### ISSUE THREAD

**Issue by Infernogd** [Weebifying/coins-in-pause-menu-geode#7]
Is there a way to have the coin blinking with better pause??

**Comment by InfernoZv** [comment]
update found another bug with better pause maybe adding the coins where I highlighted red would be better
![image](https://github.com/Weebifying/coins-in-pause-menu-geode/assets/164727301/d4795e4f-7d26-4644-b414-40a1ec066b40)

**Comment by Weebifying** [comment]
not my problem, ask tpdea :D

**Comment by InfernoZv** [comment]
Alright
